ci: update the release pipeline of the artifacts of the repo

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,7 +1,7 @@
 name: Testing
 
 on:
-  - pull_request
+  pull_request:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -14,14 +14,28 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Install Node.js
-        uses: useblacksmith/setup-node@v5
+      - name: Setup tools
+        uses: ./.github/actions/setup-tools
         with:
-          node-version: 18.x
-          cache: 'npm'
+          install-nodejs: 'true'
 
-      - name: Install Dependencies
-        run: npm ci
+      - name: Build project and capture output
+        run: npm run build > build.log 2>&1
+
+      - name: Check for build errors
+        run: |
+          if grep -q -i "error" build.log || grep -q -i "warning" build.log; then
+            echo "Build contains following errors or warnings..."
+
+            cat build.log
+
+            exit 1;
+          else
+            exit 0;
+          fi
+
+      - name: Set environment variable
+        run: export CHECK_CONTRACT_SIZE=true
 
       - name: Test
-        run: CHECK_CONTRACT_SIZE=true npx hardhat test --parallel
+        run: npm run test -- --parallel
